# Generated by Django 4.2.15 on 2024-08-13 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='apk_file_en',
            field=models.FileField(null=True, upload_to='apks/', verbose_name='APK File'),
        ),
        migrations.AddField(
            model_name='app',
            name='apk_file_fr',
            field=models.FileField(null=True, upload_to='apks/', verbose_name='APK File'),
        ),
        migrations.AddField(
            model_name='app',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='app',
            name='created_at_fr',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='app',
            name='first_screen_shot_en',
            field=models.ImageField(null=True, upload_to='f_screenshot/', verbose_name='First Screenshot'),
        ),
        migrations.AddField(
            model_name='app',
            name='first_screen_shot_fr',
            field=models.ImageField(null=True, upload_to='f_screenshot/', verbose_name='First Screenshot'),
        ),
        migrations.AddField(
            model_name='app',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='app',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='app',
            name='second_screen_shot_en',
            field=models.ImageField(null=True, upload_to='s_screenshot/', verbose_name='Second Screenshot'),
        ),
        migrations.AddField(
            model_name='app',
            name='second_screen_shot_fr',
            field=models.ImageField(null=True, upload_to='s_screenshot/', verbose_name='Second Screenshot'),
        ),
        migrations.AddField(
            model_name='app',
            name='ui_hierarchy_en',
            field=models.TextField(blank=True, null=True, verbose_name='UI Hierarchy'),
        ),
        migrations.AddField(
            model_name='app',
            name='ui_hierarchy_fr',
            field=models.TextField(blank=True, null=True, verbose_name='UI Hierarchy'),
        ),
        migrations.AddField(
            model_name='app',
            name='updated_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='app',
            name='updated_at_fr',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='app',
            name='uploaded_by_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_uploaded_by', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AddField(
            model_name='app',
            name='uploaded_by_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_uploaded_by', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AddField(
            model_name='app',
            name='video_recording_en',
            field=models.FileField(null=True, upload_to='video_recording/', verbose_name='Video Recording'),
        ),
        migrations.AddField(
            model_name='app',
            name='video_recording_fr',
            field=models.FileField(null=True, upload_to='video_recording/', verbose_name='Video Recording'),
        ),
    ]
