# Generated by Django 4.2.15 on 2024-08-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_app_apk_file_en_app_apk_file_fr_app_created_at_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='apk_file_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='apk_file_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='created_at_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='first_screen_shot_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='first_screen_shot_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='second_screen_shot_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='second_screen_shot_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='ui_hierarchy_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='ui_hierarchy_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_at_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='updated_at_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='uploaded_by_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='uploaded_by_fr',
        ),
        migrations.RemoveField(
            model_name='app',
            name='video_recording_en',
        ),
        migrations.RemoveField(
            model_name='app',
            name='video_recording_fr',
        ),
    ]
