# Generated by Django 4.2.15 on 2024-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_app_apk_file_en_remove_app_apk_file_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='screen_changed',
            field=models.BooleanField(default=False, verbose_name='Screen Changed'),
        ),
        migrations.AlterField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
