# Generated by Django 4.2.15 on 2024-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_app_screen_changed_alter_app_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='first_screen_shot',
            field=models.ImageField(blank=True, null=True, upload_to='f_screenshot/', verbose_name='First Screenshot'),
        ),
        migrations.AlterField(
            model_name='app',
            name='second_screen_shot',
            field=models.ImageField(blank=True, null=True, upload_to='s_screenshot/', verbose_name='Second Screenshot'),
        ),
        migrations.AlterField(
            model_name='app',
            name='video_recording',
            field=models.FileField(blank=True, null=True, upload_to='video_recording/', verbose_name='Video Recording'),
        ),
    ]
