version: '3.8'

services:
  backend:
    container_name: django-backend
    build: .
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - sqldb
    restart: on-failure
    environment:
      - DB_NAME=MYSQL
      - DB_USER=root
      - DB_PASSWORD=ahmed
      - DB_HOST=sqldb
      - DB_PORT=3306
    networks:
      - backend-network
    volumes:
      - ./media:/app/media
      - C:\docker_share:/app/media


  Myredis:
    image: redis:7.0.14-alpine3.18
    container_name: MyRedisServer
    networks:
      - backend-network

  celery:
    build: .
    command: celery -A project worker --loglevel=info
    depends_on:
      - Myredis
      - backend
    volumes:
      - ./media:/app/media  
      - /c/docker_share:/app/media
    networks:
      - backend-network

  sqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=MYSQL
      - MYSQL_ROOT_PASSWORD=ahmed
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

  appium:
    image: appium/appium
    container_name: appium-server
    ports:
      - "4723:4723"   
      - "5037:5037"  
    network_mode: "host" 
    restart: always
    environment:
      - APPIUM_LOG_LEVEL=info
    command: >
      bash -c "appium"

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
